sudo: required
language: python
python:
  - "3.5"
install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - python3 -m pip install lxml
  - python3 -m pip install beautifulsoup4
  - python3 -m pip install slugify
script: pytest
after_success: coveralls
